### ISSUE TITLE
Unable to get 2.x to work

### ISSUE THREAD

**Issue by mrackers** [marcusspitzmiller/QlikSenseTask#1]
I have not been able to get 2.x to work on our 2.1.1 installation of Qlik Sense. It states that -task and -wait are undefined. I am able to get the 1.x and 1.1 versions to work, but the completion codes are not correct. I also noticed that the help portion of 2.x is not displaying correctly.

![image](https://cloud.githubusercontent.com/assets/18176932/14158294/f4ab345e-f694-11e5-9216-ec1c9a828633.png)

**Comment by marcusspitzmiller** [comment]
It should be -wait:600, not -wait=600.  Check this and let me know what is not working after that, please.

**Comment by mrackers** [comment]
Sorry; I mistyped when I did the first screen capture; I re-ran it today with -wait:600 instead of -wait=600, but no change. The 2.x does not recognize -wait:600 or -task. Again the help file on 2.x does not work. I provided the exact command on 1.1 that works.
![image](https://cloud.githubusercontent.com/assets/18176932/14190506/c9e41154-f758-11e5-808e-b3279cace1c9.png)

**Comment by henrikmatz** [comment]
It think I have a similar issue.

It may help, if you could make a detailed example on how to fill out the parameters.
Let's say Qlik Sense server is called "QlikServer" and task to run is called "TaskNameToRun"

We have tested:
QlikSenseTask.exe -proxy:http://QlikServer -task:TaskNameToRun
QlikSenseTask.exe -proxy:https://QlikServer -task:TaskNameToRun

But get error "Proxy or Task undefined"

**Comment by marcusspitzmiller** [comment]
Hi, so here is what I am doing and it is working fine.  I am not sure what is going on here, but it is possible that I uploaded a bad build.  I've gone ahead and cleaned a few things up and uploaded my changes.  Please give this a try and note the syntax of my example, which i've now included in the -? and Readme on this page.  Let me know how it goes.  Thanks!

![image](https://cloud.githubusercontent.com/assets/12087678/14325640/d95335c0-fbef-11e5-968d-61cbe3a1e3aa.png)

**Comment by henrikmatz** [comment]
Thanks Marcus!

It works now, so guess it was a bug in previous release.
This is an awesome extension.

Henrik

**Comment by marcusspitzmiller** [comment]
Great!

**Comment by marcusspitzmiller** [comment]
@mrackers, can you please check if it is working for you?

**Comment by mrackers** [comment]
Just checked it and looks good. Quick question: I have a job that runs in 1.5 min, but the return code didn't show up until almost 3 minutes. Is there a way of increasing the polling for status?

**Comment by marcusspitzmiller** [comment]
I uploaded a new version that includes a -poll parameter.  Default is 30 (seconds), You should be able to set that to something like 15 or 10 to check more often.
