### ISSUE TITLE
Stopped working after we enable TLS1.2

### ISSUE THREAD

**Issue by nitin881984** [marcusspitzmiller/QlikSenseTask#29]
THe tool was working properly but after we enabled TLS1.2 and disabled TLS1.1 and 1.0, it stopped working.
The error which am getting is as below.

2021_10_08_12_57_37,Debug,"error: The underlying connection was closed: An unexpected error occurred on a receive."
2021_10_08_12_57_37,Error,"System.Exception: Couldnt connect to the server at <server name> , check that the Proxy and QRS are running.  Message: Object reference not set to an instance of an object.
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseTask.Program.Main(String[] args)"
2021_10_08_12_57_37,Information,"Returning Errorlevel 8"

Any help is appreciated

**Comment by nitin881984** [comment]
Hi Marcus,

I downloaded all the file from the release and tried to execute, but still same error.
![TLS support issue](https://user-images.githubusercontent.com/17024046/136829842-dde28cbc-2c37-40ae-9a8c-8d4780862ab3.png)


Thanks for helping me , please correct me if I am doing something wrong

**Comment by nitin881984** [comment]
I tried on one other server where the framework version was 4.8.03761, It failed there too.

Time, LogLevel, Message
2021_10_11_22_09_11,Information,"Task: QV_QS_INTEGRATION"
2021_10_11_22_09_11,Information,"Proxy: https://selfservice-alpha.intra.chrysler.com"
2021_10_11_22_09_11,Information,"Wait: 6000 seconds"
2021_10_11_22_09_11,Information,"Poll: 30 seconds"
2021_10_11_22_09_11,Information,"Log: C:\Users\NITM_s_QVService\Desktop\TLS"
2021_10_11_22_09_11,Information,"Delete Log: -90 days"
2021_10_11_22_09_11,Information,"Creating connection..."
2021_10_11_22_09_11,Debug,"Creating web connection..."
2021_10_11_22_09_11,Debug,"Creating CookierAwareWebClient..."
2021_10_11_22_09_11,Debug,"calling /qrs/about"
2021_10_11_22_09_11,Debug,"setting headers"
2021_10_11_22_09_11,Debug,"constructing query string"
2021_10_11_22_09_11,Debug,"calling https://selfservice-alpha.intra.chrysler.com/qrs/about"
2021_10_11_22_09_11,Debug,"error: The underlying connection was closed: An unexpected error occurred on a receive."
2021_10_11_22_09_11,Error,"System.Exception: Couldnt connect to the server at https://selfservice-alpha.intra.chrysler.com , check that the Proxy and QRS are running.  Message: Object reference not set to an instance of an object.
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseTask.Program.Main(String[] args)"
2021_10_11_22_09_11,Information,"Returning Errorlevel 8"

**Comment by marcusspitzmiller** [comment]
In TLS 1.2 > Server, I am pretty sure the “Enabled” value in the registry should be set to a 1, not 0xfffff (I.e. -1) right?

- Marcus
________________________________
